#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export KEYTIMEOUT=1
export PROJECTS="$HOME/projects"
export GOPATHEX="$HOME/.golang"
export GOPATHIN="$PROJECTS/golang"
export GOPATH="$GOPATHEX:$GOPATHIN"
export PATH="$HOME/bin:$GOPATHIN/bin:$GOPATHEX/bin:$PATH"
export GDRIVE="$HOME/gdrive"
export GIT_REMOTE="$GDRIVE/git"
export EDITOR="nvim"
export GIT_EDITOR="$EDITOR"
export DOTFILES="$HOME/projects/dotfiles"

export NVM_DIR="$HOME/.nvm"
which pyenv > /dev/null && eval "$(pyenv init -)"

# LAST OF ALL
#Load any local config
if [ -e "$HOME/.zshenv.local" ]; then
    source "$HOME/.zshenv.local"
fi

